// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZwdfX0R0j_Wseh1ZXv6ev_2PZlCSdOE',
    appId: '1:949956744656:web:499bde28cb10f86924d5d5',
    messagingSenderId: '949956744656',
    projectId: 'a-de-adote',
    authDomain: 'a-de-adote.firebaseapp.com',
    storageBucket: 'a-de-adote.appspot.com',
    measurementId: 'G-WVMHWKGB9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLY7ywL3fdQnepwaSpBsC30sq98uRc548',
    appId: '1:949956744656:android:ee6901cd35c418b224d5d5',
    messagingSenderId: '949956744656',
    projectId: 'a-de-adote',
    storageBucket: 'a-de-adote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFX5h79aDjIeHQkD4W28_lV_wMGYPHVA',
    appId: '1:949956744656:ios:6548f6724d3ed0e524d5d5',
    messagingSenderId: '949956744656',
    projectId: 'a-de-adote',
    storageBucket: 'a-de-adote.appspot.com',
    iosClientId: '949956744656-srld9fhjjlg1vcfofbeq70jdd2rt8kr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aDeAdote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvFX5h79aDjIeHQkD4W28_lV_wMGYPHVA',
    appId: '1:949956744656:ios:6548f6724d3ed0e524d5d5',
    messagingSenderId: '949956744656',
    projectId: 'a-de-adote',
    storageBucket: 'a-de-adote.appspot.com',
    iosClientId: '949956744656-srld9fhjjlg1vcfofbeq70jdd2rt8kr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aDeAdote',
  );
}
